prepare for merge

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,8 +2,6 @@ name: Release to NPM
 
 on:
   push:
-    branches:
-      - chore/initial-setup
     tags:
       - 'v*'
 
@@ -30,10 +28,10 @@ jobs:
           TAG_VERSION=${GITHUB_REF#refs/tags/v}
           echo "PACKAGE_VERSION: $PACKAGE_VERSION"
           echo "TAG_VERSION: $TAG_VERSION"
-#          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
-#            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
-#            exit 1
-#          fi
+          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
+            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
+            exit 1
+          fi
 
       - name: Install dependencies
         run: npm ci
@@ -48,4 +46,4 @@ jobs:
         run: npm run build:types
 
       - name: Publish to NPM
-        run: npm publish --access public --provenance --tag beta
+        run: npm publish --access public --provenance
